import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./variables.module.scss";
import { MSWCompoent } from "./_component/MSWCompenent";
import AuthSession from "./_component/AuthSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWCompoent />
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
};
export default RootLayout;
